CREATE TABLE VEHICULOS
(
	MATRICULA VARCHAR2(7),
	MARCA VARCHAR2(10) NOT NULL,
	MODELO VARCHAR2(10) NOT NULL,
	FECHA_COMPRA DATE CHECK (EXTRACT (YEAR FROM FECHA_COMPRA)>2001),
	PRECIO_DIA NUMBER(5,2),
CONSTRAINT PK_VEHICULOS PRIMARY KEY (MATRICULA),
CONSTRAINT CHK_PRECIO_DIA CHECK (PRECIO_DIA>0)
);

CREATE TABLE CLIENTES 
(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(30) NOT NULL,
	NACIONALIDAD VARCHAR2(30),
	FECHA_NAC DATE,
	DIRECCION VARCHAR2(50),
CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI)
);

CREATE TABLE ALQUILERES
(
	MATRICULA VARCHAR(7),
	DNI VARCHAR(9),
	FECHA_HORA DATE,
	NUM_DIAS NUMBER(2) NOT NULL,
	KILOMETROS NUMBER(4) DEFAULT 0,
CONSTRAINT PK_ALQUILERES PRIMARY KEY (MATRICULA, DNI, FECHA_HORA),
CONSTRAINT FK1_ALQUILERES FOREIGN KEY (MATRICULA) REFERENCES VEHICULOS(MATRICULA),
CONSTRAINT FK2_CLIENTES FOREIGN KEY (DNI) REFERENCES CLIENTES(DNI)
);

ALTER TABLE CLIENTES ADD CONSTRAINT CHK1_DNI CHECK (REGEXP_LIKE(DNI, '^[0-9]{8}-[a-z|A-Z]{1}$'));
ALTER TABLE VEHICULOS ADD CONSTRAINT CHK2_MATRICULA CHECK (REGEXP_LIKE(MATRICULA, '^[0-9]{4}[A-Z]{3}$'));
ALTER TABLE VEHICULOS ADD TOTAL_KILOMETROS NUMBER(4);




