CREATE TABLE JUGADORES 
(
	COD_JUGADOR VARCHAR2(4),
	NOMBRE VARCHAR2(30)NOT NULL,
	FECHA_NAC DATE,
	DEMARCACION VARCHAR2(10),
	COD_EQUIPO VARCHAR2(4),
CONSTRAINT FK_JUGADORES PRIMARY KEY (COD_JUGADOR)
);

CREATE TABLE EQUIPOS
(
	COD_EQUIPO VARCHAR2(4),
	NOMBRE VARCHAR2(30)NOT NULL,
	LOCALIDAD VARCHAR2(15),
CONSTRAINT FK_EQUIPOS PRIMARY KEY (COD_EQUIPO)
);

CREATE TABLE PARTIDOS 
(
	COD_PARTIDOS VARCHAR2(4),
	COD_EQUIPO_LOCAL VARCHAR2(4) NOT NULL,
	COD_EQUIPO_VISITANTE VARCHAR(4) NOT NULL,
	FECHA DATE ,
	COMPETICION VARCHAR2(4),
	JORNADA VARCHAR2(20),
CONSTRAINT PK_PARTIDOS PRIMARY KEY (COD_PARTIDOS),
CONSTRAINT FK1_COD_EQUIPO_LOCAL FOREIGN KEY (COD_EQUIPO_LOCAL) REFERENCES EQUIPOS(COD_EQUIPO),
CONSTRAINT FK2_COD_EQUIPO_VISITANTE FOREIGN KEY (COD_EQUIPO_VISITANTE) REFERENCES EQUIPOS(COD_EQUIPO),
CONSTRAINT FK1_FECHA CHECK ((EXTRACT (MONTH FROM FECHA)!=7) AND (EXTRACT(MONTH FROM FECHA)!=8)),
CONSTRAINT FK1_COMPETICION CHECK (COMPETICION  IN ('COPA','LIGA'))
);

CREATE TABLE INCIDENCIAS
(
	NUM_INCIDENCIA VARCHAR2(6),
	COD_PARTIDO VARCHAR(4),
	COD_JUGADOR VARCHAR(4),
	MINUTO NUMBER(3),
	TIPO VARCHAR2(20) NOT NULL,
CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (NUM_INCIDENCIA),
CONSTRAINT FK_COD_PARTIDO FOREIGN KEY (COD_PARTIDO) REFERENCES PARTIDOS(COD_PARTIDOS),
CONSTRAINT FK_COD_JUGADOR FOREIGN KEY (COD_JUGADOR) REFERENCES JUGADORES(COD_JUGADOR)
);



ALTER TABLE JUGADORES ADD CONSTRAINT CHK_NOMBRE CHECK (REGEXP_LIKE(NOMBRE, '^[A-Z]'));
ALTER TABLE JUGADORES ADD CONSTRAINT CHK_DEMARCACION CHECK (DEMARCACION IN ('PORTERO','DEFENSA','MEDIO','DELANTERO'));
ALTER TABLE EQUIPOS ADD CONSTRAINT CHK1_COD_EQUIPO CHECK (REGEXP_LIKE(COD_EQUIPO, '^[0-9]'));
ALTER TABLE EQUIPOS ADD GOLES_MARCADOS NUMBER(3);


