CREATE TABLE CLIENTE 
(
	DNI VARCHAR2(10) NOT NULL,
	NOMBRE VARCHAR2(25),
	APELLIDOS VARCHAR2(25),
	FECHA_NACIMIENTO DATE,
	DIRECCION VARCHAR2(50),
CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI)
);

CREATE TABLE CATEGORIA 
(
	NOMBRE VARCHAR2(50)NOT NULL,
CONSTRAINT PK_CATEGORIA PRIMARY KEY (NOMBRE)
);

CREATE TABLE PRODUCTO 
(
	NOMBRE VARCHAR2(25) NOT NULL,
	PRECIO NUMBER(5,2),
	CANTIDAD NUMBER(10),
	NOMBRE_CATEGORIA VARCHAR2(25) NOT NULL,
CONSTRAINT PK_PRODUCTO PRIMARY KEY (NOMBRE),
CONSTRAINT FK1_PRODUCTO FOREIGN KEY (NOMBRE_CATEGORIA) REFERENCES CATEGORIA(NOMBRE)
);

CREATE TABLE COMPRA
(
	DNI VARCHAR2(10) NOT NULL,
	NOMBRE VARCHAR2(25) NOT NULL,
	FECHA DATE NOT NULL,
CONSTRAINT PK_COMPRA PRIMARY KEY (DNI, NOMBRE, FECHA),
CONSTRAINT FK1_COMPRA FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI),
CONSTRAINT FK2_COMPRA FOREIGN KEY (NOMBRE) REFERENCES PRODUCTO(NOMBRE)
);
