DROP TABLE DEPARTAMENTO CASCADE CONSTRAINT;
DROP TABLE EMPLEADO CASCADE CONSTRAINT;

CREATE TABLE DEPARTAMENTO
(
	COD NUMBER(10),
	NOMBRE VARCHAR2(100),
	PRESUPUESTO NUMBER(20,6),
	GASTOS NUMBER(20,6),
CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD)
);

CREATE TABLE EMPLEADO 
(
	COD NUMBER(10),
	NIF VARCHAR2(9),
	NOMBRE VARCHAR2(100),
	APELLIDO1 VARCHAR2(100),
	APELLIDO2 VARCHAR2(100),
	COD_DEPARTAMENTO NUMBER(10),
CONSTRAINT PK_EMPLEADO PRIMARY KEY(COD),
CONSTRAINT FK_EMPLEADO FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD)
);

INSERT INTO DEPARTAMENTO VALUES (1, 'Desarrollo', 120000, 6000);
INSERT INTO DEPARTAMENTO VALUES (2, 'Sistemas', 150000, 21000);
INSERT INTO DEPARTAMENTO VALUES (3, 'Recursos Humanos', 280000, 25000);
INSERT INTO DEPARTAMENTO VALUES (4, 'Contabilidad', 110000, 3000);
INSERT INTO DEPARTAMENTO VALUES (5, 'I+D', 375000, 380000);
INSERT INTO DEPARTAMENTO VALUES (6, 'Proyectos', 0, 0);
INSERT INTO DEPARTAMENTO VALUES (7, 'Publicidad', 0, 1000);

INSERT INTO EMPLEADO VALUES (1, '32481596F', 'Aarón', 'Rivero', 'Gómez', 1);
INSERT INTO EMPLEADO VALUES (2, 'Y5575632D', 'Adela', 'Salas', 'Díaz', 2);
INSERT INTO EMPLEADO VALUES (3, 'R6970642B', 'Adolfo', 'Rubio', 'Flores', 3);
INSERT INTO EMPLEADO VALUES (4, '77705545E', 'Adrián', 'Suárez', NULL, 4);
INSERT INTO EMPLEADO VALUES (5, '17087203C', 'Marcos', 'Loyola', 'Méndez', 5);
INSERT INTO EMPLEADO VALUES (6, '38382980M', 'María', 'Santana', 'Moreno', 1);
INSERT INTO EMPLEADO VALUES (7, '80576669X', 'Pilar', 'Ruiz', NULL, 2);
INSERT INTO EMPLEADO VALUES (8, '71651431Z', 'Pepe', 'Ruiz', 'Santana', 3);
INSERT INTO EMPLEADO VALUES (9, '56399183D', 'Juan', 'Gómez', 'López', 2);
INSERT INTO EMPLEADO VALUES (10, '46384486H', 'Diego','Flores', 'Salas', 5);
INSERT INTO EMPLEADO VALUES (11, '67389283A', 'Marta','Herrera', 'Gil', 1);
INSERT INTO EMPLEADO VALUES (12, '41234836R', 'Irene','Salas', 'Flores', NULL);
INSERT INTO EMPLEADO VALUES (13, '82635162B', 'Juan Antonio','Sáez', 'Guerrero', NULL);

INSERT INTO DEPARTAMENTO VALUES (8, 'Comercial', 654123, NULL);

INSERT INTO DEPARTAMENTO VALUES(9, NULL, NULL, NULL);
UPDATE DEPARTAMENTO SET NOMBRE='Logistica', PRESUPUESTO=44513 WHERE COD=9;

INSERT INTO DEPARTAMENTO VALUES(10, NULL, NULL, NULL);
UPDATE DEPARTAMENTO SET NOMBRE='Directivo', PRESUPUESTO=2234, GASTOS=223 WHERE COD=10;

INSERT INTO EMPLEADO VALUES(14, '47208223X', 'Fran', 'Sanchez', 'Benitez', 10);

INSERT INTO EMPLEADO VALUES (15, NULL, NULL, NULL, NULL, NULL);
UPDATE EMPLEADO SET NIF='48309334Y', NOMBRE='Jesus', APELLIDO1='Arenas', APELLIDO2=NULL, COD_DEPARTAMENTO=9 WHERE COD=15;

CREATE TABLE DEPARTAMENTO_BACKUP AS (SELECT * FROM DEPARTAMENTO);

DELETE FROM DEPARTAMENTO WHERE COD=6;

DELETE FROM EMPLEADO WHERE COD=1;
DELETE FROM EMPLEADO WHERE COD=6;
DELETE FROM EMPLEADO WHERE COD=11;
DELETE FROM DEPARTAMENTO WHERE COD=1;
INSERT INTO EMPLEADO VALUES (1, '32481596F', 'Aarón', 'Rivero', 'Gómez', NULL);
INSERT INTO EMPLEADO VALUES (6, '38382980M', 'María', 'Santana', 'Moreno', NULL);
INSERT INTO EMPLEADO VALUES (11, '67389283A', 'Marta','Herrera', 'Gil', NULL);

DELETE FROM EMPLEADO WHERE COD=3;
DELETE FROM EMPLEADO WHERE COD=8;
UPDATE DEPARTAMENTO SET COD=30 WHERE NOMBRE='Recursos Humanos';
INSERT INTO EMPLEADO VALUES (3, 'R6970642B', 'Adolfo', 'Rubio', 'Flores', 30);
INSERT INTO EMPLEADO VALUES (8, '71651431Z', 'Pepe', 'Ruiz', 'Santana', 30);

UPDATE DEPARTAMENTO SET COD=40 WHERE NOMBRE='Publicidad';

--UPDATE DEPARTAMENTO SET PRECIO<2000 PRECIO=(PRECIO+50000);

DELETE FROM EMPLEADO WHERE (COD_DEPARTAMENTO=NULL);




