--DROP TABLE AUTOR ;
--DROP TABLE LIBRO CASCADE CONSTRAINT;
--DROP TABLE LIBRO_AUTOR CASCADE CONSTRAINT;
--DROP TABLE TEMA CASCADE CONSTRAINT;
--DROP TABLE PUBLICACIONES ;
--DROP TABLE EDITORIAL CASCADE CONSTRAINT;


CREATE TABLE TEMA 
(
	COD_TEMA NUMBER(20),
	DENOMINACION VARCHAR2(50),
	COD_TEMA_PADRE NUMBER(20) NOT NULL,
CONSTRAINT PK_TABLE PRIMARY KEY (COD_TEMA),
CONSTRAINT FK1_TABLE FOREIGN KEY (COD_TEMA_PADRE) REFERENCES TEMA(COD_TEMA)
);

ALTER TABLE TEMA ADD CONSTRAINT CHK1_COD_TEMA_PADRE CHECK (COD_TEMA_PADRE>COD_TEMA);

CREATE TABLE AUTOR
(
	COD_AUTOR NUMBER(20),
	NOMBRE VARCHAR2(20),
	F_NACIMIENTO DATE,
	LIBRO_PRINCIPAL NUMBER(20) NOT NULL,
CONSTRAINT PK_AUTOR PRIMARY KEY (COD_AUTOR)
);

CREATE TABLE LIBRO
(
	COD_LIBRO NUMBER(20),
	TITULO VARCHAR2(20),
	F_CREACION DATE,
	COD_TEMA NUMBER(20) NOT NULL,
	AUTOR_PRINCIPAL NUMBER(20),
CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO),
CONSTRAINT FK1_LIBRO FOREIGN KEY (COD_TEMA) REFERENCES TEMA(COD_TEMA),
CONSTRAINT FK2_LIBRO FOREIGN KEY (AUTOR_PRINCIPAL) REFERENCES AUTOR(COD_AUTOR)
);

ALTER TABLE AUTOR ADD CONSTRAINT FK1_AUTOR FOREIGN KEY (LIBRO_PRINCIPAL) REFERENCES LIBRO(COD_LIBRO);

CREATE TABLE LIBRO_AUTOR
(
	COD_LIBRO NUMBER(20),
	COD_AUTOR NUMBER(20),
	ORDEN NUMBER(20),
CONSTRAINT PK_LIBRO_AUTOR PRIMARY KEY (COD_LIBRO, COD_AUTOR),
CONSTRAINT FK1_LIBRO_AUTOR FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
CONSTRAINT FK2_LIBRO_AUTOR FOREIGN KEY (COD_AUTOR) REFERENCES AUTOR(COD_AUTOR)
);

ALTER TABLE LIBRO_AUTOR ADD CONSTRAINT CHK1_LIBRO_AUTOR CHECK (ORDEN<=5 AND ORDEN>=1);

CREATE TABLE EDITORIAL 
(
	COD_EDITORIAL NUMBER(20),
	DENOMINACION VARCHAR2(30),
CONSTRAINT PK1_EDITORIAL PRIMARY KEY (COD_EDITORIAL)
);

CREATE TABLE PUBLICACIONES 
(
	COD_EDITORIAL NUMBER(30),
	COD_LIBRO NUMBER(20),
	PRECIO NUMBER(5,2) NOT NULL,
	F_PUBLICACION DATE DEFAULT SYSDATE,
CONSTRAINT PK_PUBLICACIONES PRIMARY KEY (COD_EDITORIAL, COD_LIBRO),
CONSTRAINT FK1_PUBLICACIONES FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
CONSTRAINT FK2_PUBLICACIONES FOREIGN KEY (COD_EDITORIAL) REFERENCES EDITORIAL(COD_EDITORIAL) ON DELETE CASCADE
);

ALTER TABLE PUBLICACIONES ADD CONSTRAINT CHK1_PRECIO CHECK(PRECIO>0) 





